### ISSUE TITLE
is this a/the foundation for Debian's python3-dev?

### ISSUE THREAD

**Issue by nbehrnd** [vpoulailleau/python-dev-tools#664]
**Is your feature request related to a problem? Please describe.**
A search by `python3-dev` on pypi lists close to 700 entries.  Preparing an update of the documentation for Python's numpy ([link](https://github.com/numpy/numpy/pull/23614), I would like to know if your project is a / the foundation for Linux Debian's package `python3-dev`.

**Describe the solution you'd like**
Maybe the documentation of your project can provide a s statement in lines of "Debian's `python3-dev` benefits from this project / is unrelated to this project."  Or (if affirmative) a ribbon relaying to repology.org; the one about [markdownlint](https://github.com/markdownlint/markdownlint) may serve as an example of application.

**Describe alternatives you've considered**
As by today, [2023-04-20 Thu], Debian's package manager synaptic is not explicit about this, see the screen photo below.  A search by `python3-dev` (no quotation marks) on https://tracker.debian.org/ leads to https://tracker.debian.org/pkg/python3-defaults, and subsequently (left hand column) to https://packages.debian.org/unstable/python3-dev about the binaries.  Yet again, no explicit hint which were affirmative about a relation of your project, and the compiled package there.

**Additional context**

![synaptic_python3-dev](https://user-images.githubusercontent.com/19709084/233304470-b18db727-b161-46a0-9c64-2b0089d1b829.gif)

**Comment by vpoulailleau** [comment]
@nbehrnd No this is not the Python repository. What you are looking for is here: https://github.com/python/cpython
